### ISSUE TITLE
Try out "miette" crate in "dlint" binary

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#1024]
Currently we use `annotate-snippets` crate to display diagnostics in `dlint` and `deno lint` has its own diagnostics display API.

We should try out https://docs.rs/miette/4.2.1/miette/ which seems to be well suited for this task and is now used by SWC:
https://github.com/swc-project/swc/pull/3946

**Comment by kdy1** [comment]
Note that `Send` is required for [`SourceCode`](https://docs.rs/miette/4.2.1/miette/trait.SourceCode.html)

cc @zkat

I enabled `concurrent` feature of `swc_common` because of this bound, but deno does not use this flag and this flag is global, so I think there should be a way to use non-sync type as `SourceCode`.

Is it required because of the global hook?

**Comment by dsherret** [comment]
@kdy1 we share source text and ASTs around in an `Arc` in our LSP. I'm guessing we would just implement this trait for our `ParsedSource` struct: https://github.com/denoland/deno_ast/blob/31ef71c157d93db40dac518dfb25814b122395ca/src/parsed_source.rs#L34

**Comment by dsherret** [comment]
One thing is that we hold onto diagnostics for a long time and only surface them for certain actions in the language server. For example, we allow doing linting on files with diagnostics, but we don't allow formatting to happen if there's certain diagnostics so we check them then.
