### ISSUE TITLE
[suggestion] remove ban-untagged-ignore and add no-invalid-ignore

### ISSUE THREAD

**Issue by disizali** [denoland/deno_lint#157]
two suggestion :
1) `deno-lint-ignore` ignore all rules for the next line ( remove `ban-untagged-ignore` )
2) `deno-lint-ignore no-war` should be reported in a rule like `no-invalid-ignore`

**Comment by bartlomieju** [comment]
> 1. `deno-lint-ignore` ignore all rules for the next line ( remove `ban-untagged-ignore` )

I'm pretty much against it - if that's a wildcard ignore it may lead to unwanted supression of some diagnostics. I think requiring lint rule name to be specified is a sane requirement. 

> 2. deno-lint-ignore no-war should be reported in a rule like no-invalid-ignore

So, just rename from `ban-untagged-ignore` to `no-invalid-ignore`? I like the name, but right now unrecongnized rules are not reported - otherwise we'd end up with a lot of errors for rules that we haven't incorporated yet. I added `lint_unused_ignore_directives` setting that can be used to control this behavior.

**Comment by disizali** [comment]
>  it may lead to unwanted supression of some diagnostics.

make sense , so let's leave it as it is.

> So, just rename from ban-untagged-ignore to no-invalid-ignore? 

yeah, I also agree with the name.
I close this issue for now and after adding all the rules, I'll reopen and add this rule.
