### ISSUE TITLE
getter-return and infinite loops

### ISSUE THREAD

**Issue by callionica** [denoland/deno_lint#348]
The following code produces "Getter requires a return deno-lint(getter-return)" despite the return statement.
I wonder if it's possible for the linter to recognize that the only way out of the loop and out of the function is through the return?

I would have just ignored the linter and not opened an issue except that the linter clearly recognizes that the last line when uncommented is redundant since uncommenting it silences deno-lint(getter-return), but produces a deno-lint(no-unreachable) error instead.

```
get root(): this {
        // deno-lint-ignore no-this-alias
        let primary = this;
        while (true) {
            if (primary.parent !== undefined) {
                primary = primary.parent;
            } else {
                return primary;
            }
        }
        //return this;
    }
```

deno 1.4.0
v8 8.7.75
typescript 4.0.2
VS Code extension 2.3.1

I'm fine with a "Won't Fix" on this BTW.

**Comment by magurotuna** [comment]
Seems like that happens because `no-unreachable` analyzes control flow, but `getter-return` does not. 
`getter-return` just checks `if` and `switch` statements only, and does not analyze complex flows like infinite loops.

I think we should get the same error if we use ESLint. I'll check it.

**Comment by magurotuna** [comment]
hmm it looks like ESLint's `getter-return` _does_ analyze some control flows
https://github.com/eslint/eslint/blob/v7.10.0/lib/rules/getter-return.js#L77-L99
It checks whether the last segment is reachable or not.

So the following code would generate no error if linted by ESLint.

```js
```

**Comment by magurotuna** [comment]
I'll try to fix the `deno_lint` implementation of `getter-return`.

**Comment by magurotuna** [comment]
@kdy1 
Could I ask you a question?
As far as I looked into it, `getter-return` also has to use `ControlFlow` because in ESLint `getter-return` uses so called "Code Path Analysis" which is similar to `ControlFlow` in some ways.
Specifically, `getter-return` in ESLint reports an error if the final segment of a getter method is reachable - in other words, if a getter method returns any value, it means that the code path doesn't reach the exit of the method.

Current `ControlFlow` seems to be able to check whether statements are reachable or not, but doesn't have support for other kinds of nodes. Do you think we can make it possible for `ControlFlow` to check if an exit of a function is reachable?

(On my first thought, I just need to port "Code Path Analysis" from ESLint to deno_lint, but it looks a little hard)

**Comment by kdy1** [comment]
Of course. Just ping me on github or discord.


> Do you think we can make it possible for ControlFlow to check if an exit of a function is reachable?

I guess it's possible, but what is exit of function exactly? I'm not sure if you meant the last statement or statements like return, throw, etc.


> port "Code Path Analysis" from ESLint to deno_lint

This is impossible I guess, as there's no gc. Circular arc may work, but it will make code really dirty.

**Comment by magurotuna** [comment]
> I guess it's possible, but what is exit of function exactly? I'm not sure if you meant the last statement or statements like return, throw, etc.

I'm not 100% sure either, maybe "the exit of function" doesn't match any of such kind of stuff.

See the figure of https://eslint.org/docs/developer-guide/code-path-analysis#when-there-is-a-function.
 I think the black circle with white border is "exit". In this figure, the function reaches the "exit". 

On the other hand, looking at https://eslint.org/docs/developer-guide/code-path-analysis#forstatement-for-ever we can see there's no path to black circle with white border. This is exactly "unreachable exit".

> This is impossible I guess, as there's no gc. Circular arc may work, but it will make code really dirty.

Ah, that may be the case... we should use typed arena or something like that

**Comment by kdy1** [comment]
Checking if a statement is end of function will be very easy. There's a function named stops_execution at https://github.com/denoland/deno_lint/blob/b1375b92df244aad5997f4e9a5e5ad0f54091830/src/control_flow/mod.rs#L57.
Modifing it to check if it's `Forced` would be enough.

You can then check if the last item of function body stops execution **and** reachable (to handle forever for statements). I think `getter-return` can be implemented in this way.

**Comment by magurotuna** [comment]
That's great! I will try to implement that way. Thanks so much😆

**Comment by kdy1** [comment]
I made a mistake. I guess you should add a new method instead of modifing it.

**Comment by magurotuna** [comment]
@kdy1 
I did some attempts, but I couldn't figure out how to realize... :(
For the simplest example:
```ts
class Foo {
  get getter() {
    // no body
  }
}
```

Obviously, this example should result in `getter-return` error, so we have to make sure that this is an error using `ControlFlow`.

If we pass this code to `ControlFlow` and let the result output via `dbg!`, we get:

```
[src/control_flow/mod.rs:594] flow = ControlFlow {
    meta: {},
}
```

There's no information at all, we cannot decide the code should be error or not.

------------------------------

Another example:
```ts
class Foo {
  get getter() {
    if (bar) {
      return 1;
    }
  }
}
```

```
[src/control_flow/mod.rs:596] flow = ControlFlow {
    meta: {
        BytePos(
            49,
        ): Metadata {
            unreachable: false,
            done: Some(
                Forced,
            ),
        },
        BytePos(
            41,
        ): Metadata {
            unreachable: false,
            done: Some(
                Forced,
            ),
        },
    },
}
```

This should also be a error, because if `bar` is falsy this getter doesn't return any value.
We need to somehow ensure this is error from the above metadata.

The last example:
```ts
class Foo {
  get getter() {
    return 1;
  }
}
```

```
[src/control_flow/mod.rs:594] flow = ControlFlow {
    meta: {
        BytePos(
            28,
        ): Metadata {
            unreachable: false,
            done: Some(
                Forced,
            ),
        },
        BytePos(
            34,
        ): Metadata {
            unreachable: false,
            done: Some(
                Forced,
            ),
        },
    },
}
```

This example should be considered valid since the getter always (unconditionally) returns `1`. 
But the debug output looks very similar to that of the above example - we can't confirm which is error, which is valid.

Now I feel like much bigger change is requied to achive it. Is my thought correct?
Besides, I've found that `Scope` in `control_flow/mod.rs` has a field named `done`.
https://github.com/denoland/deno_lint/blob/b1375b92df244aad5997f4e9a5e5ad0f54091830/src/control_flow/mod.rs#L77-L78
Can it be used for `getter-return` somehow?

**Comment by kdy1** [comment]
>Obviously, this example should result in getter-return error, so we have to make sure that this is an error using  ControlFlow.
>
>If we pass this code to ControlFlow and let the result output via dbg!, we get:
>
>[src/control_flow/mod.rs:594] flow = ControlFlow {
>    meta: {},
>}
>There's no information at all, we cannot decide the code should be error or not.


In this case, I think you have to use the fact that body is empty.



>class Foo {
>  get getter() {
>    if (bar) {
>      return 1;
>    }
>  }
>}

In this case, I guess one entry is for return statement and the another is for the wrapping block statement. 


To handle this case, you should modify `control_flow.rs` slightly. https://github.com/denoland/deno_lint/blob/b1375b92df244aad5997f4e9a5e5ad0f54091830/src/control_flow/mod.rs#L159-L171

```rust
BlockKind::Function => {
    if let Done::Forced = done {
      self.mark_as_done(lo, done);
      self.scope.done = prev_done; // I'm not sure about this line. Maybe `None`?
   }
} 
```

Then you can check if the block statement of the function (stored in `Function` struct) is marked as `done`.

**Comment by magurotuna** [comment]
Great, I didn't notice one entry corresponds to a block statement (function body). It seems very useful.
I will give it a try again :)

As for the first example (no body), is there any reason that it doesn't have no metadata? I think It'd be nice if it could have an entry about block statement (function body).

**Comment by kdy1** [comment]
> As for the first example (no body), is there any reason that it doesn't have no metadata? I think It'd be nice if it could have an entry about block statement (function body).

It's just current behavior. It's empty because there's no statement which marks the block statement as `done`.
You can change it to detect empty function body and mark it as done.

**Comment by magurotuna** [comment]
I got it. Then, I'll change it so that it will be consistent with other cases.
Thanks a lot!
