### ISSUE TITLE
Linter expects constructor overloads to call super.

### ISSUE THREAD

**Issue by ihack2712** [denoland/deno_lint#548]
The lint logs: https://github.com/ihack2712/vterm/runs/1433708813
The source code: https://github.com/ihack2712/vterm/blob/dee4c012f24cec39da4fd9890f4003ac71a6981b/lib/ScreenBuffer.ts#L117

**Comment by bartlomieju** [comment]
@ihack2712 declarations are currently ommited: https://github.com/denoland/deno_lint/blob/4cb2659c8e81a225cc0673d97d91953d8c6b0a1b/src/rules/constructor_super.rs#L173-L176

This behavior was fixed in https://github.com/denoland/deno_lint/pull/470 and should be working as expected since Deno `v1.5.1`. What's the deno version that you're experiencing this problem?

**Comment by ihack2712** [comment]
I updated the CI script to use the latest version of Deno. That did work! Thanks!
