### ISSUE TITLE
Replace `markdown` and `ansi_term` with `pulldown-cmark`, `termcolor`

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#765]
In dlint we are using `markdown` and `ansi_term` to render markdown docs to the terminal, but when porting this feature to Deno CLI, it's desirable to replace these crates with ones that already exist in the dependency tree of deno cli. For compatibility dlint should probably depends on the same crates as well.
ref: https://github.com/denoland/deno/pull/11244#issuecomment-875321311

**Comment by bartlomieju** [comment]
CC @dsherret I think you mentioned that you wanted to move away from `pulldown-cmark`?

**Comment by dsherret** [comment]
Hey @magurotuna, there was a discussion today again about adding deno lint rules to the CLI docs and we thought linking to https://lint.deno.land would be sufficient enough information to give to users. The main reason is that we don't believe many people will be reading the lint rules from the CLI and linking them to https://lint.deno.land is a better experience with less for us to maintain in the long run. It would also reduce a bit of complexity because we wouldn't have to syntax highlight markdown and we wouldn't have to look into replacing ansi_term and markdown since we could remove them. What are your thoughts?

I feel bad though because you've put a lot of effort into this and done such a great job.

**Comment by magurotuna** [comment]
@dsherret 
I agree that linking to https://lint.deno.land would be sufficient, but I don't think it's that much of a burden for us to maintain CLI doc because the source of docs is identical. Also, syntax highlight for markdown could be used for other purposes like `deno doc` command output, so even if we decide to not add the feature of lint docs as CLI, the code for markdown pretty printer will probably remain in the codebase.

**Comment by magurotuna** [comment]
According to the design meeting held on July 8th (#11365), it seems like this feature is not what we should land. Close.
